#!/usr/bin/env bash
# Displays 'to infinity and beyond' and
# 'I am invincible' when receiving a SIGTERM signal
trap "echo I am invicible!!!" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
