#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
counter=0
while [ $counter -le 12 ]
do
	echo "Hour: $counter"
	k=1
	while [ $k -le 59 ]
	do
		echo "$k"
		((k++))
	done
	((counter++))
done
